import type { Metadata } from "next";

import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactQueryProvider } from "@/react-query/provider";
import { ReduxProvider } from "@/redux/provider";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";
import type { AppProps } from "next/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen antialiased")}>
        <ReduxProvider>
          <ReactQueryProvider>
            <Toaster />

            {children}
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
